BackendProject/BackendProject/Models/AppUser.cs
using Microsoft.AspNetCore.Identity;

namespace BackendProject.Models;

public class AppUser : IdentityUser
{

	public string Fullname { get; set; }
	public bool IsActive { get; set; }
	public Basket Basket { get; set; }

}

BackendProject/BackendProject/Models/Basket.cs
namespace BackendProject.Models
{
	public class Basket
	{
		public int Id { get; set; }
		public string AppUserId { get; set; }
		public AppUser AppUser { get; set; }
		public ICollection<BasketProduct> BasketProducts { get; set; }
	}
}

BackendProject/BackendProject/Models/BasketProduct.cs
namespace BackendProject.Models
{
	public class BasketProduct
	{
		public int Id { get; set; }
		public int Quantity { get; set; }
		public int BasketId { get; set; }
		public Basket Basket { get; set; }
		public int ProductId { get; set; }
		public Product Product { get; set; }
	}
}

BackendProject/BackendProject/Models/Category.cs
using BackendProject.Models.Common;

namespace BackendProject.Models;

public class Category : BaseEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
    public bool IsDeleted { get; set; }
	public ICollection<Product> Products { get; set; }

}

BackendProject/BackendProject/Models/Chef.cs
using BackendProject.Models.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace BackendProject.Models;

public class Chef : BaseEntity
{
	public int Id { get; set; }
	public string Name { get; set; }
	public string Image { get; set; }
	[NotMapped]
	public IFormFile Photo { get; set; }
	[NotMapped]
	public List<int>? SocialIds { get; set; }
	public int ExperienceInYears { get; set; }
	public bool IsDeleted { get; set; }
	public ICollection<SocialMedia> SocialMedias { get; set; }

}

BackendProject/BackendProject/Models/Contact.cs
using BackendProject.Models.Common;
using System.ComponentModel.DataAnnotations;

namespace BackendProject.Models;

public class Contact : BaseEntity
{
	public int Id { get; set; }
	public string FullName { get; set; }

	[DataType(DataType.EmailAddress)]
	public string Email { get; set; }

	public string Subject { get; set; }

	public string Message { get; set; }
}

BackendProject/BackendProject/Models/Menu.cs
using BackendProject.Models.Common;

namespace BackendProject.Models;

public class Menu : BaseEntity
{
	public int Id { get; set; }
	public string Name { get; set; }
	public decimal Price { get; set; }
	public string Image { get; set; }
	public int MenuCategoryId { get; set; }
	public MenuCategory MenuCategory { get; set; }
	public bool IsDeleted { get; set; }
}

BackendProject/BackendProject/Models/MenuCategory.cs
using BackendProject.Models.Common;

namespace BackendProject.Models;

public class MenuCategory : BaseEntity
{
	public int Id { get; set; }
	public string Name { get; set; }
	public bool IsDeleted { get; set; }
	public ICollection<Menu> Menus { get; set; }

}

BackendProject/BackendProject/Models/Product.cs
using BackendProject.Models.Common;

namespace BackendProject.Models;

public class Product : BaseEntity
{
    public int Id { get; set; }
    public string Name { get; set; }
    public double Price { get; set; }
    public int Rating { get; set; }
    public string Image { get; set; }
    public int CategoryId { get; set; }
    public Category Category { get; set; }
    public bool IsDeleted { get; set; }

}

BackendProject/BackendProject/Models/Service.cs
namespace BackendProject.Models;

public class Service
{
	public int Id { get; set; }
	public string Description { get; set; }
	public string Image { get; set; }
	public string Title { get; set; }
	public int Number { get; set; }

}

BackendProject/BackendProject/Models/Setting.cs
using System.ComponentModel.DataAnnotations;

namespace BackendProject.Models;

public class Setting
{

	public int Id { get; set; }
	[Required]
	public string Key { get; set; }
	[Required]
	public string Value { get; set; }
}

BackendProject/BackendProject/Models/Slider.cs
using Microsoft.Build.Framework;

namespace BackendProject.Models;

public class Slider
{
	public int Id { get; set; }
	public string Description { get; set; }
	public string UserImage { get; set; }
	public string UserName { get; set; }
	public string Designation { get; set; }

}

BackendProject/BackendProject/Models/SocialMedia.cs
using BackendProject.Models.Common;

namespace BackendProject.Models
{
	public class SocialMedia : BaseEntity
	{
		public int Id { get; set; }
		public string Social { get; set; }

		public int ChefId { get; set; }
		public Chef Chef { get; set; }
	}
}

BackendProject/BackendProject/ViewModels/ContactVM.cs
using System.ComponentModel.DataAnnotations;

namespace BackendProject.ViewModels
{
	public class ContactVM
	{
		[Required]
		public string FullName { get; set; }

		[Required]
		[DataType(DataType.EmailAddress)]
		public string Email { get; set; }

		[Required]
		public string Subject { get; set; }

		[Required]
		public string Message { get; set; }
	}
}

BackendProject/BackendProject/ViewModels/HeaderVM.cs
namespace BackendProject.ViewModels
{
	public class HeaderVM
	{
		public Dictionary<string, string> Settings { get; set; }
		public int Count { get; set; }
	}
}

BackendProject/BackendProject/ViewModels/HomeViewModel.cs
namespace BackendProject.ViewModels;

public class HomeViewModel
{
	public List<Slider> Sliders { get; set; }
	public List<Service> Services { get; set; }
	public List<Product> Products { get; set; }
	public List<Menu> Menus { get; set; }

}

BackendProject/BackendProject/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BackendProject.ViewModels;

public class LoginViewModel
{
	[Required, MaxLength(30)]
	public string? Username { get; set; }
	[Required, DataType(DataType.Password)]
	public string? Password { get; set; }
	public bool RememberMe { get; set; }

}

BackendProject/BackendProject/ViewModels/ShopViewModel.cs
namespace BackendProject.ViewModels;

public class ShopViewModel
{
	public List<Product> Products { get; set; }
	public List<Category> Categories { get; set; }
}

BackendProject/BackendProject/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;

namespace BackendProject.Controllers
{
	public class BlogController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Detail()
		{
			return View();
		}
	}
}

BackendProject/BackendProject/Controllers/FagController.cs
using Microsoft.AspNetCore.Mvc;

namespace BackendProject.Controllers
{
	public class FagController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}
	}
}

BackendProject/BackendProject/Views/Shared/Components/Header2/Default.cshtml
@model HeaderVM

<!-- header section start -->
<header class="header">
	<a href="#" class="logo">
		<img src="~/assets/images/@Model.Settings["HeaderLogo2"]" alt="" />
	</a>
	<!-- header navbar -->
	<ul class="navbar">
		<li class="menu-item">
			<a aria-current="page" asp-controller="Home" asp-action="Index">home</a>
		</li>
		<li class="menu-item">
			<a aria-current="page" asp-controller="About" asp-action="Index">about</a>
		</li>
		<li class="menu-item">
			<a aria-current="page" asp-controller="Menu" asp-action="Index">menu</a>
		</li>
		<li class="menu-item">
			<a aria-current="page" asp-controller="Reservation" asp-action="Index">reservation</a>
		</li>
		<li class="menu-item">
			<a href="#" class="sub-btn">
				pages <i class="fas fa-angle-down"></i>
			</a>
			<ul class="sub-menu">
				<li class="sub-item"><a aria-current="page" asp-controller="Blog" asp-action="Index">blog</a></li>
				<li class="sub-item"><a aria-current="page" asp-controller="Blog" asp-action="Detail">blog detail</a></li>
				<li class="sub-item"><a aria-current="page" asp-controller="Chef" asp-action="Index">chefs</a></li>
				<li class="sub-item"><a aria-current="page" asp-controller="Fag" asp-action="Index">fag</a></li>
			</ul>
		</li>
		<li class="menu-item">
			<a href="#">shop <i class="fas fa-angle-down"></i></a>
			<ul class="sub-menu">
				<li class="sub-item"><a aria-current="page" asp-controller="Shop" asp-action="Index">shop</a></li>
				<li class="sub-item">
					<a aria-current="page" asp-controller="Shop" asp-action="Detail">shop details</a>
				</li>
				<li class="sub-item"><a aria-current="page" asp-controller="Shop" asp-action="Cart">shop cart</a></li>
				<li class="sub-item">
					<a aria-current="page" asp-controller="Shop" asp-action="Checkout">shop checkout</a>
				</li>
			</ul>
		</li>
		<li class="menu-item">
			<a aria-current="page" asp-controller="Contact" asp-action="Index">contact</a>
		</li>
	</ul>

	<!-- header icons -->
	<div class="icons">
		<div class="search-btn-icon">			 
			<i class="fa-solid fa-user" id="search-btn"></i>
			@if (User.Identity.IsAuthenticated)
			{
				<span>@User.Identity.Name</span>
				<a asp-controller="Account" asp-action="Logout">Logout</a>  
			}
			else
			{
				<a asp-controller="Account" asp-action="Login">Login</a>  
			}
		</div>
		<div>
			<a asp-controller="Shop" asp-action="Cart">
				<i class="fa solid fa-basket-shopping" id="cart-btn"></i>
			</a>
			<span class="quantity">@Model.Count</span>
			<span style="display: none;" class="quantity2">@Model.Count</span>
		</div>

		<div>
			<i class="fas fa-bars" id="menu-btn"></i>
		</div>
	</div>
	<!-- header cart items -->
@*	<div class="cart-items-container">
		<div class="cart-item">
			<span class="fas fa-times"> </span>
			<img src="~/assets/images/s-p-11.png" alt="" />
			<div class="content">
				<h3>cart item 01</h3>
				<div class="price">$15.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"> </span>
			<img src="~/assets/images/s-p-4.png" alt="" />
			<div class="content">
				<h3>cart item 02</h3>
				<div class="price">$15.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"> </span>
			<img src="~/assets/images/s-p-5.png" alt="" />
			<div class="content">
				<h3>cart item 03</h3>
				<div class="price">$15.99/-</div>
			</div>
		</div>
		<div class="cart-item">
			<span class="fas fa-times"> </span>
			<img src="~/assets/images/s-p-7.png" alt="" />
			<div class="content">
				<h3>cart item 04</h3>
				<div class="price">$15.99/-</div>
			</div>
		</div>
		<div class="sub-total">
			<span> SUB TOTAL:</span>
			<span>$87.00</span>
		</div>
		<div class="sub-button">
			<a href="#" class="sub-btn">cehckout now</a>
			<a href="#" class="sub-btn">cehckout now</a>
		</div>
	</div>*@
	<div class="responsive-header-container">
		<div>
			<img src="~/assets/images/logo-black.png" alt="" />
		</div>
		<ul>
			<ul class="responsive-navbar">
				<li class="responsive-menu-item">
					<a href="index.html">home</a>
				</li>
				<li class="responsive-menu-item">
					<a href="about.html">about</a>
				</li>
				<li class="responsive-menu-item">
					<a href="menu.html">menu</a>
				</li>
				<li class="responsive-menu-item">
					<a href="reservation.html">reservation</a>
				</li>
				<li class="responsive-menu-item">
					<a href="#" class="sub-btn">
						pages <i class="fas fa-angle-down"></i>
					</a>
					<ul class="responsive-sub-menu">
						<li class="responsive-sub-item">
							<a href="blog.html">blog</a>
						</li>
						<li class="responsive-sub-item">
							<a href="blog-detail.html">blog detail</a>
						</li>
						<li class="responsive-sub-item">
							<a href="chef.html">chefs</a>
						</li>
						<li class="responsive-sub-item"><a href="faq.html">fag</a></li>
					</ul>
				</li>
				<li class="responsive-menu-item">
					<a href="shop.html">shop <i class="fas fa-angle-down"></i></a>
					<ul class="responsive-sub-menu">
						<li class="responsive-sub-item">
							<a href="shop.html">shop</a>
						</li>
						<li class="responsive-sub-item">
							<a href="shop-detail.html">shop details</a>
						</li>
						<li class="responsive-sub-item">
							<a href="shop-cart.html">shop cart</a>
						</li>
						<li class="responsive-sub-item">
							<a href="shop-checkout.html">checkout</a>
						</li>
					</ul>
				</li>
				<li class="responsive-menu-item">
					<a href="contact.html">contact</a>
				</li>
			</ul>
		</ul>
	</div>
</header>

<!-- header section end -->

BackendProject/BackendProject/Views/Shared/_BasketProductsPartial.cshtml
@model HeaderVM

@foreach (var item in Model.Basket.BasketProducts)
{
	<div class="cart-item">
		<span data-id="@item.Id" data-quantity="@item.Quantity" class="fas fa-times"></span>
		<img src="~/assets/images/@item.Image" alt="" />
		<div class="content">
			<h3>@item.Name</h3>
			<div class="price">$@item.Price/-</div>
		</div>
	</div>
}

BackendProject/BackendProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" href="~/assets/css/about.css" />

	<!-- font awesome cdn link -->
	<script src="https://kit.fontawesome.com/88699d56f3.js"
			crossorigin="anonymous"></script>
</head>
<body>
	<!-- scroll top start -->
	<div id="progress">
		<span id="progress-value">&#x1F815;</span>
	</div>
	<!-- scroll top end -->
	@await Component.InvokeAsync("Header");
	@RenderBody()
	@await  Component.InvokeAsync("Footer");

	<script src="~/assets/js/about.js"></script>
</body>
</html>

BackendProject/BackendProject/Views/Shared/_ProductsPartial.cshtml
@model ShopViewModel

@foreach (var product in Model.Products)
{
	<div class="shop-item">
		<div class="shop-icons">
			<i cart-id="@product.Id" class="fas fa-shopping-basket"></i>
			<i class="fas fa-heart"></i>
			<i class="fas fa-eye"></i>
		</div>
		<div class="product-img">
			<img src="~/assets/images/@product.Image" alt="" />
		</div>
		<div class="title">
			<h4>ROSTED COFFEE</h4>
			<h6>@product.Name</h6>
			<span> PRICE - $@product.Price </span>
			<span class="stars">
				@for (var i = 0; i < product.Rating; i++)
				{
					<i class="fas fa-star gold"></i>
				}

			</span>
		</div>
	</div>
}